### PR TITLE
Annotations, e.g. `@Ignore`, on functions and classes are correctly propagated

### LINKED ISSUE #318: Burst ignores @Ignore annotation on test classes
When adding the `@Ignore` annotation to a test class instead of individual tests together with the `@Burst` annotation, the `@Ignore` annotation doesn't work and the tests still run.

```
@Ignore
@Burst
class Test(
        private val testParameter: Boolean = burstValues(true, false),
) {
    @Test
    fun test() {
        error("Should be ignored")
    }
}
```

When adding the annotation to individual test methods, the `@Ignore` annotation still works as expected and skips the test.

AGP 9.0.1
Kotlin 2.3.20
Burst 2.12.0

### PR DESCRIPTION
**Pull request by oldergod**
Fixes #318

### CODE REVIEW

File: burst-kotlin-plugin/src/main/kotlin/app/cash/burst/kotlin/ClassSpecializer.kt [hunk 1]
```diff
@@ -140,6 +142,11 @@ internal class ClassSpecializer(
           createThisReceiverParameter()
         }
 
+    val burstFqName = BurstApis.burstAnnotationId.asSingleFqName()
+    created.annotations += original.annotations
+      .filter { it.type.classFqName != burstFqName }
```
Comment (oldergod) [inline burst-kotlin-plugin/src/main/kotlin/app/cash/burst/kotlin/ClassSpecializer.kt]: Not sure if we also wanna exclude `InterceptTest`, or in reverse if we only wanna allow filter `Ignore`

**Comment by dellisd** [comment]
Ooh, you just beat me to it!
https://github.com/cashapp/burst/pull/329

**Comment by oldergod** [comment]
@dellisd 180° approach though!

**Comment by JakeWharton** [comment]
Can you combine? I think I prefer this approach but Derek's tests.

File: burst-kotlin-plugin/src/main/kotlin/app/cash/burst/kotlin/FunctionSpecializer.kt [hunk 2]
```diff
@@ -209,6 +209,7 @@ internal class FunctionSpecializer(
         }
 
     result.annotations += original.testAnnotation.asAnnotation()
+    result.annotations += original.function.annotations.map { it.deepCopyWithSymbols() }
```
Comment (oldergod) [inline burst-kotlin-plugin/src/main/kotlin/app/cash/burst/kotlin/FunctionSpecializer.kt:212]: New addition I had to make after I ported Derek's tests

File: burst-kotlin-plugin-tests/src/test/kotlin/app/cash/burst/kotlin/BurstKotlinPluginTest.kt [hunk 3]
```diff
@@ -197,6 +198,44 @@ class BurstKotlinPluginTest {
     sampleLog.clear()
   }
 
+  @Test
+  fun classAnnotationsArePropagatedToSubclasses() {
```
Comment (JakeWharton) [inline burst-kotlin-plugin-tests/src/test/kotlin/app/cash/burst/kotlin/BurstKotlinPluginTest.kt]: Delete now?

**Review by JakeWharton — APPROVED** [review]

File: burst-kotlin-plugin-tests/src/test/kotlin/app/cash/burst/kotlin/BurstKotlinPluginTest.kt (hunk 3 above)
Comment (oldergod) [reply burst-kotlin-plugin-tests/src/test/kotlin/app/cash/burst/kotlin/BurstKotlinPluginTest.kt]: done

**Review by dellisd — APPROVED** [review]
